### ISSUE TITLE
Caution: /dev/ URLs can be crawled

### ISSUE THREAD

**Issue by jonom** [dylangrech92/seotoolbox#32]
I noticed /dev/ links are getting crawled on a site I'm working on:

![screen shot 2016-10-13 at 4 47 52 pm](https://cloud.githubusercontent.com/assets/1079425/19371057/ea828ef8-9164-11e6-825a-267d14226918.png)

I'm guessing this happened because I have BetterNavigator installed, which includes a link to /dev/. It looks like the crawler is going on to request all the links in the dev menu which could be quite dangerous.

Maybe should introduce a blacklist Config setting for the crawler? Could start it off with `dev/` and `Security/`. Or is it possible for the crawler to request pages anonymously (more like Google), by not sending any cookies in the request? I'm guessing it's not...

**Comment by dylangrech92** [comment]
Try by setting:

'''yaml
SEOTestSiteTreeController:
  ignore_paths:
    - 'dev/'
'''

I forgot to include docs for it. Good catch!

**Comment by jonom** [comment]
That did the trick! Thanks for your prompt support! I now have:

```yml
SEOTestSiteTreeController:
  ignore_paths:
    - 'dev\/'
    - 'Security\/'
    - 'admin\/'
    - '\?'
```

The '\?' is a bit extreme but stops the crawler following debugging links from the navigator.

I can close this unless you want to leave it as a reminder to add a note in the docs about this feature?

**Comment by dylangrech92** [comment]
I'll add them right now and close it soon. Thanks again :+1:
